drop tables when the query beggins
EderNaylor/Data_science_trainee pull request #10
Opened 2022-12-04 01:22 UTC by EderNaylor

![image](https://user-images.githubusercontent.com/72780990/205469486-45aa7228-f764-476a-bd41-04f03d603a1c.png)

2022-12-04 01:38 UTC, DRMD431LU commented on asignacion_db.sql
> +);
y la linea al final ? >:V

2022-12-04 01:39 UTC, EderNaylor commented on asignacion_db.sql
> +);
Se fue de sabático

2022-12-04 02:01 UTC, DRMD431LU requested changes

2022-12-04 02:01 UTC, DRMD431LU commented on asignacion_db.sql
> +DROP TABLE flokzu;
![image](https://user-images.githubusercontent.com/31089639/205470394-34f4b6af-9114-4025-ac4d-2d5f1152eee6.png)
el colocar el drop sin verificar la existencia genera error

2022-12-04 02:01 UTC, DRMD431LU commented on asignacion_db.sql
> +    clave_de_llamada_id INT,
debes seguir el mismo patron si se llama "clave_de_llamada_id" en llave foranea deberia llamarse "clave_de_llamada_id" en la tabla referenciada, no debe existir discrepancia en los nombres.

2022-12-04 04:12 UTC, DRMD431LU requested changes

2022-12-04 04:12 UTC, DRMD431LU commented on asignacion_db.sql
> +CREATE TABLE IF NOT EXISTS flokzu_psbaja (
el nombre de la tabla me gustaba mas antes

2022-12-04 04:12 UTC, DRMD431LU commented on asignacion_db.sql
> +    clave_llamada INT NOT NULL UNIQUE,
aqui si deberia llevar el _id aunque estas usando la palabra "clave" para identificar una llave, no esta mal pero en ese caso ninguna otra columna que no fuera llave primaria o foranea debera llevar la palabra "clave"

2022-12-04 04:12 UTC, DRMD431LU commented on asignacion_db.sql
> +        FOREIGN KEY(clave_llamada) REFERENCES crm(clave_llamada)
estas llamando a tus foraneas _id y a tus primarias clave_ asi que aqui clave llamada deberia llevar el sufijo _id no ?

2022-12-04 04:12 UTC, DRMD431LU commented on asignacion_db.sql
> +    clave_llamada INT,
me parece que hay errores en esta tabla.

2022-12-04 04:12 UTC, DRMD431LU commented on asignacion_db.sql
> +    clave_llamada INT,
lo mismo si estas poniendo el prefijo clave_ a tus primarias entonces matricula deberia llamarse clave_matricula no unicamente matricula

2022-12-05 06:18 UTC, DRMD431LU approved these changes

2022-12-05 06:18 UTC, merged